const express = require('express')
const router = express.Router()

router.get('/login',)
router.post('/register',)
router.get('/register',)
router.post('/register',)
router.get('/home')
router.get('/profil')
router.get('/profil/playlist')
router.get('/song-list')
router.get('/artist-list')
router.get('/play/:id')
router.get('/admin/song')
router.get('/admin/artist')
router.get('/admin/song/add')
router.post('/admin/song/add')
router.get('/admin/song/edit/:id')
router.post('/admin/song/edit/:id')
router.get('/admin/song/delete')
